export const cityHospitalsData = {
    Lahore: {
        image: "/img/cities/lahore.jpg",
        description: "The cultural capital of Pakistan, known for its world-class medical facilities.",
        hospitals: [
            {
                id: "lhr-1",
                name: "Shaukat Khanum Memorial Cancer Hospital",
                type: "Cancer Specialty",
                specialties: ["Oncology", "Radiation Therapy", "Surgical Oncology", "Hematology"],
                rating: 4.9,
                reviews: 2450,
                beds: 195,
                established: 1994,
                address: "7-A Block R-3, Johar Town, Lahore",
                phone: "+92-42-35945100",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Chemotherapy", "Radiation", "Lab", "Pharmacy", "Blood Bank"],
                description: "Pakistan's premier cancer treatment center, providing state-of-the-art cancer care with a mission to serve all patients regardless of their ability to pay.",
                image: "/img/shoukatkhanam.jpg",
            },
            {
                id: "lhr-2",
                name: "Hameed Latif Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Orthopedics", "Pediatrics", "Gynecology"],
                rating: 4.7,
                reviews: 1890,
                beds: 350,
                established: 1994,
                address: "14 Abu Bakar Block, New Garden Town, Lahore",
                phone: "+92-42-35862301",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "NICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy", "Blood Bank"],
                description: "A leading multi-specialty hospital in Lahore, renowned for exceptional care in cardiology, women's health, and surgical services.",
                image: "/img/hameed latif.jpg",
            },
            {
                id: "lhr-3",
                name: "Mayo Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurosurgery", "Gastroenterology", "Urology", "ENT"],
                rating: 4.6,
                reviews: 1650,
                beds: 400,
                established: 1986,
                address: "152-G/1, Canal Bank, Johar Town, Lahore",
                phone: "+92-42-35300091",
                emergency: true,
                doctors: 250,
                facilities: ["ICU", "CCU", "Dialysis", "Endoscopy", "Radiology", "Rehabilitation"],
                description: "One of Lahore's most trusted healthcare institutions, offering comprehensive medical services with cutting-edge technology.",
                image: "/img/mayo.jpg",
            },
            {
                id: "lhr-4",
                name: "Service Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/service.jpg",
            },
            {
                id: "lhr-5",
                name: "Lahore General Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/lahore general.jpg",
            },
            {
                id: "lhr-6",
                name: "Cardiology Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/cardiology.jpg",
            },
            {
                id: "lhr-7", 
                name: "Lahore Care Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/lahore care.jpg",
            },
            {
                id: "lhr-8",
                name: "Noor Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/noor.jpg",
            },
            {
                id: "lhr-9",
                name: "Saleem Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/saleem.jpg",
            },
            {
                id: "lhr-10",
                name: "Jinnah Hospital",
                type: "Multi-Specialty",
                specialties: ["General Surgery", "Dermatology", "Pulmonology", "Psychiatry"],
                rating: 4.5,
                reviews: 1200,
                beds: 300,
                established: 2002,
                address: "132/3, L Block, DHA Phase 1, Lahore",
                phone: "+92-42-111-051-051",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Emergency", "Lab", "Imaging", "Pharmacy", "Ambulance"],
                description: "A state-of-the-art facility offering premium healthcare in the heart of DHA, Lahore.",
                image: "/img/jinnah.jpg",
            },

        ],
    },

    Karachi: {
        image: "/img/cities/karachi.jpg",
        description: "Pakistan's largest city and economic hub with numerous top-tier hospitals.",
        hospitals: [
            {
                id: "khi-1",
                name: "Aga Khan University Hospital",
                type: "Teaching Hospital",
                specialties: ["Cardiology", "Oncology", "Neurology", "Transplant Surgery", "Pediatrics"],
                rating: 4.9,
                reviews: 3200,
                beds: 700,
                established: 1985,
                address: "Stadium Road, Karachi",
                phone: "+92-21-111-911-911",
                emergency: true,
                doctors: 500,
                facilities: ["ICU", "NICU", "Transplant Center", "Cancer Center", "Emergency", "Helipad"],
                description: "A JCI-accredited institution, consistently ranked as one of the best hospitals in Pakistan and South Asia.",
                image: "/img/agha khan karachi.jpg",
            },
            {
                id: "khi-2",
                name: "Liaquat National Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiac Surgery", "Nephrology", "Neurosurgery", "Orthopedics"],
                rating: 4.7,
                reviews: 2100,
                beds: 650,
                established: 1955,
                address: "Stadium Road, Karachi",
                phone: "+92-21-111-456-456",
                emergency: true,
                doctors: 350,
                facilities: ["ICU", "CCU", "Dialysis Center", "Nuclear Medicine", "Blood Bank"],
                description: "One of the oldest and most respected hospitals in Karachi, offering world-class medical and surgical care.",
                image: "/img/liaqaut national.jpg",
            },
            {
                id: "khi-3",
                name: "South City Hospital",
                type: "Multi-Specialty",
                specialties: ["Gynecology", "General Surgery", "Internal Medicine", "Pediatrics"],
                rating: 4.6,
                reviews: 1800,
                beds: 200,
                established: 2003,
                address: "Block A, Clifton, Karachi",
                phone: "+92-21-35862301",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "NICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A modern, patient-centric hospital providing quality healthcare services in Clifton.",
                image: "/img/south city karachi.jpg",
            },
            {
                id: "khi-4",
                name: "Dr.Ziauddin Hospital",
                type: "Charitable Hospital",
                specialties: ["Oncology", "Orthopedics", "Pediatrics", "General Surgery", "Ophthalmology"],
                rating: 4.8,
                reviews: 2800,
                beds: 300,
                established: 2007,
                address: "Plot 3-A, Sector 47, Korangi, Karachi",
                phone: "+92-21-111-111-880",
                emergency: true,
                doctors: 280,
                facilities: ["ICU", "Blood Bank", "Dialysis", "Chemotherapy", "Imaging", "Lab"],
                description: "Pakistan's largest private-sector free hospital, providing completely free-of-charge healthcare to millions.",
                image: "/img/dr.ziauddin karachi.jpg",
            },
            {
                id: "khi-5",
                name: "National Medical Hospital",
                type: "Charitable Hospital",
                specialties: ["Oncology", "Orthopedics", "Pediatrics", "General Surgery", "Ophthalmology"],
                rating: 4.8,
                reviews: 2800,
                beds: 300,
                established: 2007,
                address: "Plot 3-A, Sector 47, Korangi, Karachi",
                phone: "+92-21-111-111-880",
                emergency: true,
                doctors: 280,
                facilities: ["ICU", "Blood Bank", "Dialysis", "Chemotherapy", "Imaging", "Lab"],
                description: "Pakistan's largest private-sector free hospital, providing completely free-of-charge healthcare to millions.",
                image: "/img/national medical karachi.jpg",
            },
            {
                id: "khi-6",
                name: "Jinnah Post Graduate Hospital",
                type: "Charitable Hospital",
                specialties: ["Oncology", "Orthopedics", "Pediatrics", "General Surgery", "Ophthalmology"],
                rating: 4.8,
                reviews: 2800,
                beds: 300,
                established: 2007,
                address: "Plot 3-A, Sector 47, Korangi, Karachi",
                phone: "+92-21-111-111-880",
                emergency: true,
                doctors: 280,
                facilities: ["ICU", "Blood Bank", "Dialysis", "Chemotherapy", "Imaging", "Lab"],
                description: "Pakistan's largest private-sector free hospital, providing completely free-of-charge healthcare to millions.",
                image: "/img/jinnah post karachi.jpg",
            },
            {
                id: "khi-7",
                name: "Civil Hospital",
                type: "Charitable Hospital",
                specialties: ["Oncology", "Orthopedics", "Pediatrics", "General Surgery", "Ophthalmology"],
                rating: 4.8,
                reviews: 2800,
                beds: 300,
                established: 2007,
                address: "Plot 3-A, Sector 47, Korangi, Karachi",
                phone: "+92-21-111-111-880",
                emergency: true,
                doctors: 280,
                facilities: ["ICU", "Blood Bank", "Dialysis", "Chemotherapy", "Imaging", "Lab"],
                description: "Pakistan's largest private-sector free hospital, providing completely free-of-charge healthcare to millions.",
                image: "/img/civil.jpg",
            },
            {
                id: "khi-8",
                name: "Abbasi Shaheed Hospital",
                type: "Charitable Hospital",
                specialties: ["Oncology", "Orthopedics", "Pediatrics", "General Surgery", "Ophthalmology"],
                rating: 4.8,
                reviews: 2800,
                beds: 300,
                established: 2007,
                address: "Plot 3-A, Sector 47, Korangi, Karachi",
                phone: "+92-21-111-111-880",
                emergency: true,
                doctors: 280,
                facilities: ["ICU", "Blood Bank", "Dialysis", "Chemotherapy", "Imaging", "Lab"],
                description: "Pakistan's largest private-sector free hospital, providing completely free-of-charge healthcare to millions.",
                image: "/img/abbasi karachi.jpg",
            },
            {
                id: "khi-9",
                name: "sindh Govt Hospital",
                type: "Charitable Hospital",
                specialties: ["Oncology", "Orthopedics", "Pediatrics", "General Surgery", "Ophthalmology"],
                rating: 4.8,
                reviews: 2800,
                beds: 300,
                established: 2007,
                address: "Plot 3-A, Sector 47, Korangi, Karachi",
                phone: "+92-21-111-111-880",
                emergency: true,
                doctors: 280,
                facilities: ["ICU", "Blood Bank", "Dialysis", "Chemotherapy", "Imaging", "Lab"],
                description: "Pakistan's largest private-sector free hospital, providing completely free-of-charge healthcare to millions.",
                image: "/img/sindh karachi.jpg",
            },
            {
                id: "khi-10",
                name: "National Institute of Cardio Disease",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/national karachi.jpg",
            },
        ],
    },

    Islamabad: {
        image: "/img/cities/islamabad.jpg",
        description: "The capital city of Pakistan, home to some of the country's finest medical institutions.",
        hospitals: [
            {
                id: "isb-1",
                name: "Pakistan Institute of Medical Sciences",
                type: "Multi-Specialty",
                specialties: ["Cardiac Surgery", "Organ Transplant", "Oncology", "Neurosurgery", "IVF"],
                rating: 4.8,
                reviews: 2500,
                beds: 550,
                established: 1987,
                address: "Pitras Bukhari Road, H-8/4, Islamabad",
                phone: "+92-51-111-846-846",
                emergency: true,
                doctors: 400,
                facilities: ["ICU", "Transplant Center", "Cardiac Center", "Fertility Clinic", "Helipad"],
                description: "A JCI-accredited hospital and one of the most advanced healthcare facilities in the federal capital.",
                image: "/img/pakistan islamabad.jpg",
            },
            {
                id: "isb-2",
                name: "Capital Hospital CDA",
                type: "Government Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Orthopedics", "Gynecology", "Pediatrics"],
                rating: 4.3,
                reviews: 1500,
                beds: 900,
                established: 1985,
                address: "G-8/3, Islamabad",
                phone: "+92-51-9261170",
                emergency: true,
                doctors: 600,
                facilities: ["ICU", "Emergency", "Burns Center", "Dialysis", "Lab", "Blood Bank"],
                description: "The largest government hospital in Islamabad, serving millions of patients annually.",
                image: "/img/capital islamabad.jpg",
            },
            {
                id: "isb-3",
                name: "Federal Govt Services Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/federal islamabad.jpg",
            },
            {
                id: "isb-4",
                name: "National Institute service Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/national islamabad.jpg",
            },
            {
                id: "isb-5",
                name: "Nuclear Oncoloy & Radiotherapy Institute",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/nuclear islamabad.jpg",
            },
            {
                id: "isb-6",
                name: "Advanceed International Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/advanced islamabad.jpg",
            },
            {
                id: "isb-7",
                name: "Shahida khaliq Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/shahidakhaliq.jpg",
            },
            {
                id: "isb-8",
                name: "Capital International Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/capital international islamabad.jpg",
            },
            {
                id: "isb-9",
                name: "Medcity International Hospital & Plastic Surgery",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/medcity islamabad.jpg",
            },
            {
                id: "isb-10",
                name: "General Practice Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "General Surgery", "Dermatology"],
                rating: 4.5,
                reviews: 1100,
                beds: 250,
                established: 2010,
                address: "F-10 Markaz, Islamabad",
                phone: "+92-51-2113355",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "CCU", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A modern hospital in the heart of Islamabad, known for personalized care and advanced diagnostics.",
                image: "/img/general islamabad.jpg",
            },
        ],
    },

    Rawalpindi: {
        image: "/img/cities/rawalpindi.jpg",
        description: "The twin city of Islamabad, with a rich military medical heritage.",
        hospitals: [
            {
                id: "rwp-1",
                name: "Holy Family Hospital (CMH)",
                type: "Military Hospital",
                specialties: ["General Surgery", "Orthopedics", "Internal Medicine", "Gynecology"],
                rating: 4.7,
                reviews: 1800,
                beds: 1200,
                established: 1905,
                address: "The Mall Road, Rawalpindi",
                phone: "+92-51-9270614",
                emergency: true,
                doctors: 450,
                facilities: ["ICU", "CCU", "Trauma Center", "Burns Center", "Blood Bank", "Rehab"],
                description: "One of the oldest and largest military hospitals in South Asia with over a century of service.",
                image: "/img/holy rawalpindi.jpg",
            },
            {
                id: "rwp-2",
                name: "Benezir Bhutto Hospital",
                type: "Teaching Hospital",
                specialties: ["Cardiology", "Nephrology", "Pulmonology", "Gastroenterology"],
                rating: 4.4,
                reviews: 1300,
                beds: 800,
                established: 1948,
                address: "Satellite Town, Rawalpindi",
                phone: "+92-51-9290301",
                emergency: true,
                doctors: 350,
                facilities: ["ICU", "Emergency", "Dialysis", "Lab", "Pharmacy", "Blood Bank"],
                description: "A premier teaching hospital affiliated with Rawalpindi Medical University, providing exemplary healthcare.",
                image: "/img/benezir rawalpindi.jpg",
            },
            {
                id: "rwp-3",
                name: "PAK Emirates Milletery Hospital",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/pak rawalpindi.jpg",
            },
            {
                id: "rwp-4",
                name: "Rawalpindi Teaching Hospital",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/teaching rawalpindi.jpg",
            }
            ,{
                id: "rwp-5",
                name: "Rawalpindi Institute of Cardiology",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/institute rawalpindi.jpg",
            },
            {
                id: "rwp-6",
                name: "Maryam Memorial Hospital",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/maryam rawalpindi.jpg",
            },
            {
                id: "rwp-7",
                name: "Primax MedicalComplex",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/primax rawalpindi.jpg",
            },
            {
                id: "rwp-8",
                name: "Hanif Medical Complex",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/hanif rawalpindi.jpg",
            },
            {
                id: "rwp-9",
                name: "Nusrat Hospital Rawalpindi",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/nusrat rawalpindi.jpg",
            },
            {
                id: "rwp-10",
                name: "Medical Hospital",
                type: "Welfare Hospital",
                specialties: ["Orthopedics", "Urology", "ENT", "Ophthalmology", "Dermatology"],
                rating: 4.5,
                reviews: 1000,
                beds: 500,
                established: 1971,
                address: "Westridge, Rawalpindi",
                phone: "+92-51-9271091",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Surgical Suite", "Radiology", "Lab", "Pharmacy"],
                description: "A trusted healthcare institution serving armed forces personnel and civilians with quality care.",
                image: "/img/medical rawalpindi.jpg",
            },
        ],
    },

    Faisalabad: {
        image: "/img/cities/faisalabad.jpg",
        description: "The textile capital of Pakistan, with growing healthcare infrastructure.",
        hospitals: [
            {
                id: "fsd-1",
                name: "Allied Hospital Faisalabad",
                type: "Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Gynecology", "Pediatrics", "Orthopedics"],
                rating: 4.4,
                reviews: 1100,
                beds: 1000,
                established: 1962,
                address: "Abdali Road, Faisalabad",
                phone: "+92-41-9210090",
                emergency: true,
                doctors: 400,
                facilities: ["ICU", "Emergency", "Burns Center", "Dialysis", "Lab", "Blood Bank"],
                description: "The largest teaching hospital in Faisalabad, affiliated with Punjab Medical College.",
                image: "/img/Allied fsd.jpg",
            },
            {
                id: "fsd-2",
                name: "Allied Hspital 2",
                type: "Cardiac Specialty",
                specialties: ["Interventional Cardiology", "Cardiac Surgery", "Electrophysiology"],
                rating: 4.6,
                reviews: 900,
                beds: 300,
                established: 2000,
                address: "Serena Chowk, Faisalabad",
                phone: "+92-41-9200081",
                emergency: true,
                doctors: 80,
                facilities: ["CCU", "Cardiac Cath Lab", "Cardiac Surgery", "Echo Lab", "Rehab"],
                description: "The premier cardiac care facility in the Faisalabad region with specialized heart treatment.",
                image: "/img/allied fsd 2.jpg",
            },
            {
                id: "fsd-3",
                name: "Govt General Hospital Samanabad",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/govt fsd.jpg",
            },
            {
                id: "fsd-4",
                name: "Faisalabad Institute of Cardiology",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/institute fsd.jpg",
            },
            {
                id: "fsd-5",
                name: "Children Hospital Faisalabad",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/children fsd.jpg",
            },
            {
                id: "fsd-6",
                name: "Shifa International Hospital",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/shifa fsd.jpg",
            },
            {
                id: "fsd-7",
                name: "National Hospital",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/aziz fsd.jpg",
            },
            {
                id: "fsd-8",
                name: "Mujahid Hospital",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/mujahid fsd.jpg",
            },
            {
                id: "fsd-9",
                name: "Aziz Fatima  Hospital",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/national fsd.jpg",
            },
            {
                id: "fsd-10",
                name: " America Hospital",
                type: "Multi-Specialty",
                specialties: ["Neurology", "Gastroenterology", "Urology", "Pulmonology"],
                rating: 4.3,
                reviews: 750,
                beds: 200,
                established: 2005,
                address: "Jaranwala Road, Faisalabad",
                phone: "+92-41-8713700",
                emergency: true,
                doctors: 120,
                facilities: ["ICU", "Endoscopy", "Dialysis", "MRI", "Pharmacy"],
                description: "A modern private hospital providing quality healthcare with advanced technology.",
                image: "/img/ameica fsd.jpg",
            },
        ],
    },

    Gujranwala: {
        image: "/img/cities/peshawar.jpg",
        description: "The historic frontier city with renowned medical institutions.",
        hospitals: [
            {
                id: "guj-1",
                name: "DHQ Hospital Gujranwala",
                type: "Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Pediatrics", "Orthopedics", "Ophthalmology"],
                rating: 4.3,
                reviews: 1400,
                beds: 1500,
                established: 1927,
                address: "Hospital Road, Peshawar",
                phone: "+92-91-9211430",
                emergency: true,
                doctors: 500,
                facilities: ["ICU", "Trauma Center", "Burns Center", "Blood Bank", "Lab", "Pharmacy"],
                description: "The largest hospital in KPK province, serving millions across the province and tribal areas.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-2",
                name: "Govt Civil Hospital ",
                type: "Teaching Hospital",
                specialties: ["Cardiac Surgery", "Nephrology", "Neurosurgery", "Oncology"],
                rating: 4.5,
                reviews: 1200,
                beds: 1200,
                established: 1999,
                address: "Hayatabad, Phase 4, Peshawar",
                phone: "+92-91-9217140",
                emergency: true,
                doctors: 400,
                facilities: ["ICU", "CCU", "Transplant Center", "Dialysis", "Nuclear Medicine"],
                description: "A modern teaching hospital with advanced facilities including organ transplant services.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-3",
                name: "Social Security Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-4",
                name: "Medical College Teaching Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-5",
                name: "CMH Gujranwala",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-6",
                name: "Gujranwala Medical & Dental Complex",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-7",
                name: "GINUM Hospital Gujranwala",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-8",
                name: "Care Well Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-9",
                name: "Punjab Medical Complex",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "guj-10",
                name: "Chaudhry Muhammad Akram Teaching and Research Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
                rating: 4.6,
                reviews: 950,
                beds: 350,
                established: 2004,
                address: "Phase 5, Hayatabad, Peshawar",
                phone: "+92-91-5812884",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "Cardiac Cath Lab", "MRI", "CT Scan", "Pharmacy", "Ambulance"],
                description: "A leading private hospital known for cardiac care and minimally invasive surgeries.",
                image: "/img/svg/hospital.svg",
            },
        ],
    },

    Multan: {
        image: "/img/cities/multan.jpg",
        description: "The City of Saints, with a growing network of quality healthcare facilities.",
        hospitals: [
            {
                id: "mlt-1",
                name: "Nishtar Hospital Emergency",
                type: "Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Orthopedics", "Gynecology", "Ophthalmology"],
                rating: 4.4,
                reviews: 1300,
                beds: 1700,
                established: 1953,
                address: "Nishtar Road, Multan",
                phone: "+92-61-9210073",
                emergency: true,
                doctors: 500,
                facilities: ["ICU", "Emergency", "Burns Center", "Blood Bank", "Lab", "Rehab"],
                description: "The largest hospital in South Punjab, serving as a referral center for millions of patients.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "mlt-2",
                name: "Nishtar Hospital",
                type: "Cardiac Specialty",
                specialties: ["Interventional Cardiology", "Cardiac Surgery", "Electrophysiology"],
                rating: 4.6,
                reviews: 800,
                beds: 250,
                established: 2010,
                address: "Nishtar Road, Multan",
                phone: "+92-61-9210111",
                emergency: true,
                doctors: 70,
                facilities: ["CCU", "Cardiac Cath Lab", "CSICU", "Echo Lab", "Cardiac Rehab"],
                description: "The leading cardiac care center in South Punjab, equipped with modern cardiac interventional tools.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "mlt-3",
                name: "Nishtar Medical University",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-4",
                name: "Minar Multan Institute",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-5",
                name: "WAPDA Hospital Multan",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-6",
                name: "Combined Milletery Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-7",
                name: " Medical Links International Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-8",
                name: "Ijaz Hospital Multan",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-9",
                name: "Multan Medical Mission Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "mlt-10",
                name: "South Punjab Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Nephrology", "Urology", "ENT", "Dermatology"],
                rating: 4.5,
                reviews: 700,
                beds: 300,
                established: 1995,
                address: "Nishtar Road, Multan",
                phone: "+92-61-4513801",
                emergency: true,
                doctors: 150,
                facilities: ["ICU", "Dialysis", "Endoscopy", "MRI", "Pharmacy"],
                description: "A well-regarded private hospital offering comprehensive medical and surgical services.",
                image: "/img/svg/hospital.svg",
            },
        ],
    },

    Bahawalpur: {
        image: "/img/cities/quetta.jpg",
        description: "The capital of Balochistan, serving as the healthcare hub for the largest province.",
        hospitals: [
            {
                id: "bhw-1",
                name: "Bahawalpur Victoria Hospital",
                type: "Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Gynecology", "Pediatrics", "Orthopedics"],
                rating: 4.2,
                reviews: 800,
                beds: 700,
                established: 1976,
                address: "Sariab Road, Quetta",
                phone: "+92-81-2821613",
                emergency: true,
                doctors: 250,
                facilities: ["ICU", "Emergency", "Lab", "Blood Bank", "Pharmacy", "Ambulance"],
                description: "The primary teaching hospital in Balochistan, affiliated with Bolan Medical College.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "bhw-2",
                name: "Sir Sadiq Abbasi Hospital",
                type: "Military Hospital",
                specialties: ["General Surgery", "Orthopedics", "Internal Medicine", "Ophthalmology"],
                rating: 4.5,
                reviews: 650,
                beds: 600,
                established: 1940,
                address: "Quetta Cantonment, Quetta",
                phone: "+92-81-9201560",
                emergency: true,
                doctors: 180,
                facilities: ["ICU", "CCU", "Surgical Suite", "Trauma Center", "Blood Bank"],
                description: "A premier military healthcare institution serving the armed forces and civilians in Balochistan.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "bhw-3",
                name: "MID-WEST Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-4",
                name: "Nawab Sir Sadiq Khan Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-5",
                name: "Fatima Jinnah Hospital Bahawalpur",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-6",
                name: "Jubilee Female Hospital ",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-7",
                name: "CMH Bahawalpur",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-8",
                name: "Hadi Surgimed Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-9",
                name: "City Hospital Bahawalpur",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
             {
                id: "bhw-10",
                name: "Zubair Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.3,
                reviews: 500,
                beds: 150,
                established: 2005,
                address: "Jinnah Road, Quetta",
                phone: "+92-81-2828301",
                emergency: true,
                doctors: 80,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "A trusted private hospital providing quality healthcare in the heart of Quetta.",
                image: "/img/svg/hospital.svg",
            },
        ],
    },

    Sialkot: {
        image: "/img/cities/sialkot.jpg",
        description: "The sports goods capital of Pakistan, with improving medical services.",
        hospitals: [
            {
                id: "slk-1",
                name: "Allama Iqbal Memorial Hospital",
                type: "Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Gynecology", "Pediatrics"],
                rating: 4.3,
                reviews: 700,
                beds: 600,
                established: 1974,
                address: "Khawaja Safdar Road, Sialkot",
                phone: "+92-52-4265600",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "Emergency", "Lab", "Blood Bank", "Pharmacy"],
                description: "The main teaching hospital in Sialkot, serving the healthcare needs of the region.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-2",
                name: "Govt Sardar Begum Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-3",
                name: "THQ Hospital Sambrial",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            
            {
                id: "slk-4",
                name: "THQ Hospital Pasur",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-5",
                name: "THQ Hospital Kotli Loharan",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-6",
                name: "Al-Noor Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-7",
                name: "Dr.Tassuaduq's Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-8",
                name: "CMH Combined City Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-9",
                name: "Kiran International Hospital",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "slk-10",
                name: "Muhammadi Hospital Sialkot",
                type: "Multi-Specialty",
                specialties: ["Cardiology", "Orthopedics", "Urology", "ENT"],
                rating: 4.4,
                reviews: 550,
                beds: 250,
                established: 2008,
                address: "Paris Road, Sialkot",
                phone: "+92-52-4600111",
                emergency: true,
                doctors: 100,
                facilities: ["ICU", "Cardiac Lab", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern private hospital offering specialized medical treatment with advanced equipment.",
                image: "/img/svg/hospital.svg",
            },
        ],
    },

    Karachi: {
        image: "/img/cities/hyderabad.jpg",
        description: "The second largest city in Sindh, with important medical education centers.",
        hospitals: [
            {
                id: "krc-1",
                name: "Jinnah Post Graduate Medical College",
                type: "Teaching Hospital",
                specialties: ["General Medicine", "Surgery", "Gynecology", "Pediatrics", "Orthopedics"],
                rating: 4.3,
                reviews: 900,
                beds: 1100,
                established: 1951,
                address: "Jamshoro Road, Hyderabad",
                phone: "+92-22-9213305",
                emergency: true,
                doctors: 350,
                facilities: ["ICU", "Emergency", "Burns Center", "Blood Bank", "Lab", "Pharmacy"],
                description: "A major teaching hospital in Sindh, affiliated with Liaquat University of Medical and Health Sciences.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-2",
                name: "Civil Hospital Karachi",
                type: "Teaching Hospital",
                specialties: ["Cardiology", "Nephrology", "Neurology", "Gastroenterology"],
                rating: 4.5,
                reviews: 700,
                beds: 500,
                established: 1997,
                address: "Hala Road, Hyderabad",
                phone: "+92-22-2030181",
                emergency: true,
                doctors: 200,
                facilities: ["ICU", "CCU", "Dialysis", "MRI", "CT Scan", "Pharmacy"],
                description: "A modern teaching hospital with advanced specialties and research facilities.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-3",
                name: "Abbasi Shaheed Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-4",
                name: "Sindh Govt Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-5",
                name: "National Institute of Cardio Diseases",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-6",
                name: "Liaquat National Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-7",
                name: "South CityHospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-8",
                name: "National Medical Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-9",
                name: "Dr.Ziauddin Hospital",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
            {
                id: "krc-10",
                name: "Agha Khan University",
                type: "Multi-Specialty",
                specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Gynecology"],
                rating: 4.4,
                reviews: 600,
                beds: 120,
                established: 2003,
                address: "Market Road, Hyderabad",
                phone: "+92-22-2780051",
                emergency: true,
                doctors: 70,
                facilities: ["ICU", "Lab", "Radiology", "Pharmacy", "Emergency"],
                description: "Part of the respected Aga Khan network, delivering quality healthcare services in Hyderabad.",
                image: "/img/svg/hospital.svg",
            },
        ],
    },
};


export const cities = Object.keys(cityHospitalsData);

export const getSyncedHospitals = () => {
    if (typeof window === "undefined") return cityHospitalsData;

    try {
        const stored = localStorage.getItem("docfind_hospitals");
        if (!stored) return cityHospitalsData;

        const localData = JSON.parse(stored);
        const merged = { ...cityHospitalsData };
        let hasChanges = false;

        Object.keys(cityHospitalsData).forEach((city) => {
            // If the city doesn't exist in local data (newly added city in code),
            // merged already has it from cityHospitalsData. We just note change.
            if (!localData[city]) {
                hasChanges = true;
                return;
            }

            // Sync images and descriptions from master code (usually better to trust code for assets)
            merged[city].image = cityHospitalsData[city].image;
            merged[city].description = cityHospitalsData[city].description;

            const masterHospitals = cityHospitalsData[city].hospitals;
            const localHospitalsMap = new Map(localData[city].hospitals.map(h => [h.id, h]));

            const mergedHospitals = masterHospitals.map(masterH => {
                const localH = localHospitalsMap.get(masterH.id);
                if (localH) {
                    // Merge: Keep master structure but allow local overrides ONLY for editable fields
                    // The user can only edit 'name' and 'beds' via the UI.
                    // We must prioritize Master for everything else (description, type, etc.)
                    // so that code changes to hospital-data/page.js are reflected immediately.
                    return {
                        ...masterH,
                        name: localH.name || masterH.name,
                        beds: localH.beds || masterH.beds,
                        // image: masterH.image // Already in masterH
                    };
                }
                // Hospital exists in Master but not Local -> New hospital added!
                hasChanges = true;
                return masterH;
            });

            merged[city].hospitals = mergedHospitals;
        });

        // If we found new data in Master that wasn't in Local, update Local
        if (hasChanges) {
            localStorage.setItem("docfind_hospitals", JSON.stringify(merged));
        }

        return merged;

    } catch (e) {
        console.error("Failed to sync hospitals data", e);
        return cityHospitalsData;
    }
};
