"use client";
import Image from "next/image";
import { useState } from "react";

const MedicinePage = () => {
    const [searchTerm, setSearchTerm] = useState("");

    const medicines = [
        // Pain Medicines
        {
            id: 21,
            name: "Calpol ",
            description: "Fast-acting formula for headaches and muscle pain.",
            image: "/img/pain1.jpg",
            rating: 5,
            reviews: 128,
            price: "Rs.70-80",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 22,
            name: "Brufen",
            description: "Topical relief for muscle soreness.",
            image: "/img/pain2.jpg",
            rating: 4,
            reviews: 88,
            price: "Rs.60-70",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 23,
            name: "Catafalm",
            description: "Long term relief for joint pain.",
            image: "/img/pain3.jpg",
            rating: 5,
            reviews: 156,
            price: "Rs.170-190",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 24,
            name: "Naproxen",
            description: "Targeted release for migraines.",
            image: "/img/pain4.jpg",
            rating: 4,
            reviews: 230,
            price: "Rs.470-500",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 25,
            name: "Ponstan",
            description: "Specific formula for back aches.",
            image: "/img/pain5.jpg",
            rating: 4,
            reviews: 90,
            price: "Rs.30-40",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 26,
            name: "Aceclofenac",
            description: "Extra strength for severe pain.",
            image: "/img/pain6.jpg",
            rating: 5,
            reviews: 310,
            price: "Rs.510-560",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 27,
            name: "Ketoprofen",
            description: "Relief for nerve related pain.",
            image: "/img/pain7.jpg",
            rating: 4,
            reviews: 115,
            price: "Rs.150-1200",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 28,
            name: "Tramadol",
            description: "Specialized for arthritis pain.",
            image: "/img/pain8.jpg",
            rating: 5,
            reviews: 189,
            price: "Rs.230-250",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 29,
            name: "Asprin(protect 100)",
            description: "Muscle relaxant and pain reliever.",
            image: "/img/pain9.jpg",
            rating: 4,
            reviews: 76,
            price: "Rs.25-150",
            type: "Tablet",
            sickness: "Pain",
        },
        {
            id: 30,
            name: "Napadoc",
            description: "Instant relief spray for injuries.",
            image: "/img/pain10.jpg",
            rating: 4,
            reviews: 99,
            price: "Rs.480-550",
            type: "Tablet",
            sickness: "Pain",
        },



        // Fever Medicines
        {
            id: 11,
            name: "Panadol",
            description: "Rapid relief from fever and body aches.",
            image: "/img/fever1.webp",
            rating: 4,
            reviews: 89,
            price: "Rs.70",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 12,
            name: "Mortin",
            description: "Fast acting syrup for high fever.",
            image: "/img/fever2.jpg",
            rating: 5,
            reviews: 210,
            price: "Rs.30-40",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 13,
            name: "Brufen",
            description: "Keeps body temperature under control.",
            image: "/img/fever3.jpg",
            rating: 4,
            reviews: 78,
            price: "Rs.60-70",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 14,
            name: "Asprin",
            description: "Effective active fever reducer.",
            image: "/img/fever4.jpg",
            rating: 5,
            reviews: 134,
            price: "Rs.60-160",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 15,
            name: "Voltaren D 50",
            description: "Sleep well while fighting fever.",
            image: "/img/fever5.jpg",
            rating: 4,
            reviews: 56,
            price: "Rs.240-450",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 16,
            name: "Neproxen",
            description: "Daily support during seasonal fevers.",
            image: "/img/fever6.jpg",
            rating: 3,
            reviews: 45,
            price: "Rs.100-480",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 17,
            name: "Ponstan",
            description: "Combats viral fever symptoms.",
            image: "/img/fever7.jpg",
            rating: 5,
            reviews: 99,
            price: "Rs.30-40",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 18,
            name: "Paracetamol & Ibuprofen",
            description: "Standard paracetamol for reliable relief.",
            image: "/img/fever8.jpg",
            rating: 5,
            reviews: 500,
            price: "Rs.500-750",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 19,
            name: "Surbex",
            description: "Cooling effect for high temperatures.",
            image: "/img/fever9.jpg",
            rating: 4,
            reviews: 112,
            price: "Rs.400-450",
            type: "Tablet",
            sickness: "Fever",
        },
        {
            id: 20,
            name: "Arinac(fort)",
            description: "Holistic fever management.",
            image: "/img/fever10.jpg",
            rating: 4,
            reviews: 67,
            price: "Rs.140-150",
            type: "Tablet",
            sickness: "Fever",
        },
        // Sugar / Diabetes Medicines
        {
            id: 1,
            name: "Metformin",
            description: "Helps maintain healthy blood sugar levels naturally.",
            image: "/img/sugar1.jpg",
            rating: 4,
            reviews: 72,
            price: "Rs.18-360",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 2,
            name: "GlipiCare",
            description: "Complete daily support for diabetic health.",
            image: "/img/sugar2.jpg",
            rating: 5,
            reviews: 45,
            price: "Rs.128-500",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 3,
            name: "Forxiga",
            description: "Advanced formula for glucose metabolism.",
            image: "/img/sugar11.jpg",
            rating: 4,
            reviews: 89,
            price: "Rs.400-640",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 4,
            name: "sitagliptin januvia",
            description: "Nutritional support for insulin sensitivity.",
            image: "/img/sugar4.jpg",
            rating: 5,
            reviews: 120,
            price: "Rs.300-740",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 5,
            name: "Linagliptin",
            description: "Herbal blend to reduce sugar cravings.",
            image: "/img/sugar5.jpg",
            rating: 3,
            reviews: 34,
            price: "Rs.350-410",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 6,
            name: "Januvia-vs-Tradjenta",
            description: "Standard care for blood sugar management.",
            image: "/img/sugar6.jpg",
            rating: 5,
            reviews: 300,
            price: "Rs.2350-4000",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 7,
            name: "Invokana",
            description: "Essential vitamins for diabetic needs.",
            image: "/img/sugar7.jpg",
            rating: 4,
            reviews: 90,
            price: "Rs.400",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 8,
            name: "Glumetza",
            description: "Quick action for balanced sugar levels.",
            image: "/img/sugar10.jpg",
            rating: 4,
            reviews: 67,
            price: "Rs.75",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 9,
            name: "Sitamet",
            description: "Maximum strength glucose defense.",
            image: "/img/sugar11.webp",
            rating: 5,
            reviews: 156,
            price: "Rs.288",
            type: "Tablet",
            sickness: "Sugar",
        },
        {
            id: 10,
            name: "Getryl",
            description: "Supports pancreas health and function.",
            image: "/img/sugar12.jpg",
            rating: 4,
            reviews: 44,
            price: "Rs.617-650",
            type: "Tablet",
            sickness: "Sugar",
        },


        // Stomach Medicines
        {
            id: 31,
            name: "Omeprazole",
            description: "Promotes digestive health and balances gut flora.",
            image: "/img/stomach1.jpg",
            rating: 4,
            reviews: 112,
            price: "Rs.160-180",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 32,
            name: "Osoeprazole",
            description: "Controls acidity and heartburn.",
            image: "/img/stomach2.jpg",
            rating: 5,
            reviews: 145,
            price: "Rs.190-230",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 33,
            name: "Pantoprazole",
            description: "Soothing relief for gastric issues.",
            image: "/img/stomach3.jpg",
            rating: 4,
            reviews: 89,
            price: "Rs.540-1150",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 34,
            name: "Zantac",
            description: "High potency probiotics.",
            image: "/img/stomach4.jpg",
            rating: 5,
            reviews: 200,
            price: "Rs.90-110",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 35,
            name: "Famotidine",
            description: "General stomach ache relief.",
            image: "/img/stomach5.jpg",
            rating: 3,
            reviews: 56,
            price: "Rs.150-170",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 36,
            name: "Domperidone",
            description: "Relieves bloating and gas.",
            image: "/img/stomach6.jpg",
            rating: 4,
            reviews: 110,
            price: "Rs.170-200",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 37,
            name: "Matoclopramide",
            description: "Enzymes for better digestion.",
            image: "/img/stomach7.jpg",
            rating: 4,
            reviews: 78,
            price: "Rs.40-50",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 38,
            name: "Loperamide",
            description: "Complete care for your gut.",
            image: "/img/stomach8.jpg",
            rating: 5,
            reviews: 132,
            price: "Rs.70-80",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 39,
            name: "Ulsanic",
            description: "Long lasting acidity protection.",
            image: "/img/stomach9.jpg",
            rating: 4,
            reviews: 95,
            price: "Rs.70-89",
            type: "Tablet",
            sickness: "Stomach",
        },
        {
            id: 40,
            name: "Activated Charcoal",
            description: "Natural digestive enzymes.",
            image: "/img/stomach10.jpg",
            rating: 4,
            reviews: 67,
            price: "Rs.250-5800",
            type: "Tablet",
            sickness: "Stomach",
        },

        // Other misc medicines from original list...
        {
            id: 41,
            name: "Ascorbic Acid",
            description: "Immune system support with natural citrus extracts.",
            image: "/img/immunity1.png",
            rating: 4,
            reviews: 85,
            price: "Rs.940-1100",
            type: "Tablet",
            sickness: "Immunity",
        },
        {
            id: 42,
            name: "Allergy Defense",
            description: "Non-drowsy 24-hour relief from seasonal allergies.",
            image: "/img/allergy1.jpg",
            rating: 5,
            reviews: 240,
            price: "Rs.4-40",
            type: "Tablet",
            sickness: "Allergy",
        },
        {
            id: 43,
            name: "Low-dose Asprin",
            description: "Heart health support with high-potency EPA & DHA.",
            image: "/img/heart.jpg",
            rating: 4,
            reviews: 96,
            price: "Rs.120-140",
            type: "Tablet",
            sickness: "Heart",
        },
        {
            id: 44,
            name: "Melatonin",
            description: "Natural blend of valerian root and melatonin for deep sleep.",
            image: "/img/sleep1.jpg",
            rating: 5,
            reviews: 156,
            price: "Rs.900-990",
            type: "Tablet",
            sickness: "Sleep",
        },
        {
            id: 45,
            name: "Hydrocortisone Cream",
            description: "Soothing relief for skin irritation and eczema.",
            image: "/img/skin1.jpg",
            rating: 5,
            reviews: 201,
            price: "Rs.50-60",
            type: "Tablet",
            sickness: "Skin",
        },
        {
            id: 46,
            name: "ultra Glucosamine",
            description: "Support for joint mobility and comfort.",
            image: "/img/joints1.jpg",
            rating: 4,
            reviews: 65,
            price: "Rs.6000-14000",
            type: "Tablet",
            sickness: "Joints",
        },
        {
            id: 47,
            name: "Loratadine",
            description: "Non-drowsy 24-hour relief from seasonal allergies.",
            image: "/img/allergy2.jpg",
            rating: 5,
            reviews: 240,
            price: "Rs.70-80",
            type: "Tablet",
            sickness: "Allergy",
        },
        {
            id: 48,
            name: "Fexofenadine",
            description: "General stomach ache relief.",
            image: "/img/allergy3.jpg",
            rating: 3,
            reviews: 56,
            price: "Rs.300-320",
            type: "Tablet",
            sickness: "Allergy",
        },

        // Asthma Medicines
        {
            id: 49,
            name: "Monticare 5mg",
            description: "Montelukast sodium for asthma and allergy relief.",
            image: "/img/asthma1.jpg",
            rating: 4,
            reviews: 32,
            price: "Rs.330",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 50,
            name: "Medkast 10mg",
            description: "Effective management of asthma and seasonal allergies.",
            image: "/img/asthma2.webp",
            rating: 4,
            reviews: 28,
            price: "Rs.525",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 51,
            name: "Montair 10mg",
            description: "Prevents asthma attacks and treats hay fever.",
            image: "/img/asthma3.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.337",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 52,
            name: "Montair 5mg",
            description: "Lower dosage maintenance for asthma control.",
            image: "/img/asthma4.jpg",
            rating: 4,
            reviews: 21,
            price: "Rs.238",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 53,
            name: "Asthiven 10mg",
            description: "Relieves symptoms of asthma and allergic rhinitis.",
            image: "/img/asthma5.jpg",
            rating: 4,
            reviews: 19,
            price: "Rs.209-280",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 54,
            name: "Asthiven 5mg",
            description: "Chewable tablet for easy intake.",
            image: "/img/asthma6.jpg",
            rating: 4,
            reviews: 15,
            price: "Rs.139",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 55,
            name: "Freehale 10mg",
            description: "Helps keep airways open for easier breathing.",
            image: "/img/asthma7.jpg",
            rating: 3,
            reviews: 12,
            price: "Rs.440",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 56,
            name: "MNTK 10mg",
            description: "Generic Montelukast for cost-effective treatment.",
            image: "/img/asthma8.jpg",
            rating: 4,
            reviews: 34,
            price: "Rs.764",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 57,
            name: "Fylod 400mg",
            description: "Doxofylline for asthma and COPD treatment.",
            image: "/img/asthma9.jpg",
            rating: 4,
            reviews: 22,
            price: "Rs.275",
            type: "Tablet",
            sickness: "Asthma",
        },
        {
            id: 58,
            name: "Monteluke DX",
            description: "Combination therapy for improved lung health.",
            image: "/img/asthma10.jpg",
            rating: 4,
            reviews: 18,
            price: "Rs.78",
            type: "Tablet",
            sickness: "Asthma",
        },

        // Cancer Medicines
        {
            id: 59,
            name: "Femara 2.5mg (Letrozole)",
            description: "Common for hormone-positive breast cancer.",
            image: "/img/cancer1.jpg",
            rating: 5,
            reviews: 42,
            price: "Rs.3000-11000",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 60,
            name: "Glivec 100mg (Imatinib)",
            description: "Very effective for CML & GIST.",
            image: "/img/cancer2.jpg",
            rating: 4,
            reviews: 35,
            price: "Rs.80000",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 61,
            name: "Glivec 400mg (Imatinib)",
            description: "Strong targeted therapy.",
            image: "/img/cancer3.jpg",
            rating: 4,
            reviews: 28,
            price: "Rs.140000",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 62,
            name: "Capecitabine (Xelocel 500mg)",
            description: "Oral chemo for colorectal/breast cancer.",
            image: "/img/cancer4.jpg",
            rating: 4,
            reviews: 51,
            price: "Rs.32900",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 63,
            name: "Lonsurf 15mg/6.14mg",
            description: "Used for advanced colon cancer.",
            image: "/img/cancer5.jpg",
            rating: 4,
            reviews: 12,
            price: "Rs.280000",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 64,
            name: "Tucaxen 150mg (Tucatinib)",
            description: "HER2+ breast cancer agent.",
            image: "/img/cancer6.jpg",
            rating: 4,
            reviews: 9,
            price: "Varies",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 65,
            name: "Regonix 40mg (Regorafenib)",
            description: "Advanced cancer oral treatment.",
            image: "/img/cancer7.jpg",
            rating: 4,
            reviews: 14,
            price: "Rs.255000",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 66,
            name: "Afanix (Afatinib 40mg)",
            description: "Lung cancer targeted therapy.",
            image: "/img/cancer8.jpg",
            rating: 4,
            reviews: 21,
            price: "Rs.44000",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 67,
            name: "Nolvadex (Tamoxifen 10mg)",
            description: "Hormone therapy for breast cancer.",
            image: "/img/cancer9.jpg",
            rating: 4,
            reviews: 132,
            price: "Rs.260-300",
            type: "Tablet",
            sickness: "Cancer",
        },
        {
            id: 68,
            name: "Lezra / Letrozone",
            description: "More affordable letrozole options.",
            image: "/img/cancer10.jpg",
            rating: 4,
            reviews: 55,
            price: "Rs.2300-4100",
            type: "Tablet",
            sickness: "Cancer",
        },

        // Kidney Disease Medicines
        {
            id: 69,
            name: "Ketosteril 100s",
            description: "CKD support & slows progression.",
            image: "/img/kidney1.jpg",
            rating: 4,
            reviews: 62,
            price: "Rs.21000",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 70,
            name: "Renavel C 800mg (Sevelamer)",
            description: "Lowers phosphate in CKD.",
            image: "/img/kidney2.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.2965",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 71,
            name: "Sevla 400mg (Sevelamer)",
            description: "Phosphate binder in CKD.",
            image: "/img/kidney3.jpg",
            rating: 4,
            reviews: 38,
            price: "Rs.1470",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 72,
            name: "Selcarb 800mg (Sevelamer)",
            description: "Phosphate binding tablet.",
            image: "/img/kidney4.jpg",
            rating: 4,
            reviews: 29,
            price: "Rs.2965",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 73,
            name: "Neovel 800mg (Sevelamer)",
            description: "CKD phosphate control.",
            image: "/img/kidney5.jpg",
            rating: 4,
            reviews: 33,
            price: "Rs.2500",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 74,
            name: "Urocit-K Tablets",
            description: "Prevents stones/alkalinizes urine.",
            image: "/img/kidney6.jpg",
            rating: 4,
            reviews: 51,
            price: "Rs.900-1300",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 75,
            name: "Mirabet 25/50mg",
            description: "Kidney support (brand listing).",
            image: "/img/kidney7.jpg",
            rating: 4,
            reviews: 18,
            price: "Rs.1527-2102",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 76,
            name: "K-ston Tablets",
            description: "Kidney stone support/pH balance.",
            image: "/img/kidney8.jpg",
            rating: 4,
            reviews: 24,
            price: "Rs.1050",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 77,
            name: "RenaVit Multivitamin",
            description: "Vitamins for renal patients.",
            image: "/img/kidney9.jpg",
            rating: 4,
            reviews: 15,
            price: "Rs.650",
            type: "Tablet",
            sickness: "Kidney Disease",
        },
        {
            id: 78,
            name: "Ketoalfa Tablets",
            description: "CKD support (listed).",
            image: "/img/kidney10.jpg",
            rating: 4,
            reviews: 27,
            price: "Rs.494",
            type: "Tablet",
            sickness: "Kidney Disease",
        },

        // Hepatitis Medicines

        {
            id: 89,
            name: "Hilvel",
            description: "Pan-genotypic HCV cure; widely prescribed.",
            image: "/img/hepatitis1.jpg",
            rating: 5,
            reviews: 110,
            price: "Rs.15000-16000",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 90,
            name: "Velpaget",
            description: "Effective across all Hepatitis C genotypes.",
            image: "/img/hepatitis2.jpg",
            rating: 5,
            reviews: 95,
            price: "Rs.19000",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 91,
            name: "Epclusa (Brand)",
            description: "Premium brand; high cure rates.",
            image: "/img/hepatitis3.jpg",
            rating: 5,
            reviews: 42,
            price: "Rs.80000-100000",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 92,
            name: "Hepevir 400mg",
            description: "Generic Sofosbuvir; often combined with other agents.",
            image: "/img/hepatitis4.jpg",
            rating: 4,
            reviews: 32,
            price: "Rs.5800",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 93,
            name: "Hepaldi 400mg",
            description: "Affordable generic Sofosbuvir.",
            image: "/img/hepatitis5.jpg",
            rating: 4,
            reviews: 28,
            price: "Rs.5800",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 94,
            name: "Cure-C 400mg",
            description: "Cost-effective option for Hepatitis C.",
            image: "/img/hepatitis6.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.5800",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 95,
            name: "Ecavir 0.5mg",
            description: "Standard HBV antiviral.",
            image: "/img/hepatitis7.jpg",
            rating: 4,
            reviews: 62,
            price: "Rs.3000-15000",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 96,
            name: "Centaurus 0.5mg",
            description: "Generic option for Hepatitis B.",
            image: "/img/hepatitis8.jpg",
            rating: 4,
            reviews: 21,
            price: "Rs.1200",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 97,
            name: "Hilfo-B",
            description: "HBV suppressive therapy.",
            image: "/img/hepatitis9.jpg",
            rating: 4,
            reviews: 38,
            price: "Rs.3500",
            type: "Tablet",
            sickness: "Hepatitis",
        },
        {
            id: 98,
            name: "Abriva Plus",
            description: "Antiviral combination for Hepatitis C.",
            image: "/img/hepatitis10.jpg",
            rating: 5,
            reviews: 130,
            price: "Rs.10350-11500",
            type: "Tablet",
            sickness: "Hepatitis",
        },

        // Migraine Medicines
        {
            id: 99,
            name: "Panadol Migraine",
            description: "Targeted relief for migraine pain.",
            image: "/img/migraine1.jpg",
            rating: 5,
            reviews: 120,
            price: "Rs.3800-5200",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 100,
            name: "Sitan 500/85mg",
            description: "Effective combination for severe headaches.",
            image: "/img/migraine2.jpg",
            rating: 5,
            reviews: 95,
            price: "Rs.1500",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 101,
            name: "Napsum 85/500mg",
            description: "Relief from migraine symptoms.",
            image: "/img/migraine3.jpg",
            rating: 5,
            reviews: 80,
            price: "Rs.1200",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 102,
            name: "Zolmig 2.5mg",
            description: "Fast-acting migraine relief.",
            image: "/img/migraine4.jpg",
            rating: 5,
            reviews: 65,
            price: "Rs.470",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 103,
            name: "Ziptan 2.5mg",
            description: "Helps alleviate migraine attacks.",
            image: "/img/migraine5.jpg",
            rating: 4,
            reviews: 50,
            price: "Rs.300",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 104,
            name: "Imigran / Sumatriptan",
            description: "Standard treatment for acute migraine.",
            image: "/img/migraine6.jpg",
            rating: 5,
            reviews: 110,
            price: "Rs.800-1000",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 105,
            name: "Askprol M",
            description: "Migraine management tablet.",
            image: "/img/migraine7.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.480",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 106,
            name: "Migril",
            description: "Effective for migraine with aura.",
            image: "/img/migraine8.jpg",
            rating: 4,
            reviews: 70,
            price: "Rs.50-60",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 107,
            name: "Triptan 2.5mg",
            description: "Specific migraine pain reliever.",
            image: "/img/migraine9.jpg",
            rating: 5,
            reviews: 85,
            price: "Rs.190-900",
            type: "Tablet",
            sickness: "Migraine",
        },
        {
            id: 108,
            name: "Topagen",
            description: "Prevention and treatment of migraine.",
            image: "/img/migraine10.jpg",
            rating: 4,
            reviews: 55,
            price: "Rs.900+",
            type: "Tablet",
            sickness: "Migraine",
        },

        // Alzheimer Medicines
        {
            id: 109,
            name: "Memril 10mg (Memantine)",
            description: "Popular memantine tablet for moderate Alzheimer’s.",
            image: "/img/alzheimer1.jpg",
            rating: 5,
            reviews: 45,
            price: "Rs.1500",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 110,
            name: "Zexa 10mg (Memantine)",
            description: "Memantine for cognitive symptoms.",
            image: "/img/alzheimer2.jpg",
            rating: 4,
            reviews: 32,
            price: "Rs.3150-3539",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 111,
            name: "Alzentine 10mg (Memantine)",
            description: "Another memantine brand (often cheaper).",
            image: "/img/alzheimer3.jpg",
            rating: 4,
            reviews: 28,
            price: "Rs.1200",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 112,
            name: "Donep 5mg (Donepezil)",
            description: "Common cholinesterase inhibitor for memory.",
            image: "/img/alzheimer4.jpg",
            rating: 4,
            reviews: 55,
            price: "Rs.519",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 113,
            name: "Donep 10mg (Donepezil)",
            description: "Higher strength version for memory support.",
            image: "/img/alzheimer5.jpg",
            rating: 5,
            reviews: 40,
            price: "Rs.724",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 114,
            name: "Riveme 1.5mg (Rivastigmine)",
            description: "Rivastigmine form for dementia symptoms.",
            image: "/img/alzheimer6.jpg",
            rating: 4,
            reviews: 35,
            price: "Rs.670",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 115,
            name: "Exelon Capsules 1.5mg",
            description: "Rivastigmine (imported brand), higher rating.",
            image: "/img/alzheimer7.jpg",
            rating: 5,
            reviews: 60,
            price: "Rs.3761-3960",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 116,
            name: "Exelon Capsules 3mg",
            description: "Stronger rivastigmine dose.",
            image: "/img/alzheimer8.jpg",
            rating: 5,
            reviews: 52,
            price: "Rs.3657-3850",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 117,
            name: "Contine 10mg",
            description: "Memantine alternative (local brand).",
            image: "/img/alzheimer9.jpg",
            rating: 4,
            reviews: 25,
            price: "Rs.950",
            type: "Tablet",
            sickness: "Alzheimer",
        },
        {
            id: 118,
            name: "Afdol 10mg",
            description: "Another memantine option on marketplace.",
            image: "/img/alzheimer10.jpg",
            rating: 4,
            reviews: 30,
            price: "Rs.665",
            type: "Tablet",
            sickness: "Alzheimer",
        },

        // Hypertension Medicines
        {
            id: 119,
            name: "Exforge HCT 10/160/12.5mg",
            description: "Combo for strong BP control.",
            image: "/img/hypertension1.jpg",
            rating: 5,
            reviews: 65,
            price: "Rs.940-1050",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 120,
            name: "Exforge HCT 5/160/25mg",
            description: "Triple combo for hypertension.",
            image: "/img/hypertension2.jpg",
            rating: 5,
            reviews: 58,
            price: "Rs.1880-2090",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 121,
            name: "Co-Diovan (Valsartan/HCTZ)",
            description: "Popular ARB + diuretic.",
            image: "/img/hypertension3.jpg",
            rating: 5,
            reviews: 70,
            price: "Rs.1576",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 122,
            name: "Covance H 10/160/25mg",
            description: "Triple combination tablet.",
            image: "/img/hypertension4.jpg",
            rating: 4,
            reviews: 42,
            price: "Rs.368-409",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 123,
            name: "Valtec AMH 10/160/25mg",
            description: "Triple combo (Amlodipine + Valsartan + Diuretic).",
            image: "/img/hypertension5.jpg",
            rating: 4,
            reviews: 35,
            price: "Rs.409",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 124,
            name: "Avsar Plus 160/5/25mg",
            description: "Combo: ARB + CCB + Diuretic.",
            image: "/img/hypertension6.jpg",
            rating: 4,
            reviews: 48,
            price: "Rs.450",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 125,
            name: "Covam 5/160mg",
            description: "Amlodipine + Valsartan.",
            image: "/img/hypertension7.jpg",
            rating: 4,
            reviews: 55,
            price: "Rs.615",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 126,
            name: "Cuziper 2.5mg",
            description: "Beta-blocker (Bisoprolol).",
            image: "/img/hypertension8.jpg",
            rating: 4,
            reviews: 30,
            price: "Rs.44",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 127,
            name: "Capoten 25mg (Captopril)",
            description: "ACE inhibitor for BP control.",
            image: "/img/hypertension9.jpg",
            rating: 4,
            reviews: 80,
            price: "Rs.360",
            type: "Tablet",
            sickness: "Hypertension",
        },
        {
            id: 128,
            name: "Sartan H (Losartan + HCTZ)",
            description: "ARB + Diuretic option.",
            image: "/img/hypertension10.jpg",
            rating: 4,
            reviews: 50,
            price: "Rs.350",
            type: "Tablet",
            sickness: "Hypertension",
        },

        // Diabetes Medicines (New Addition)
        {
            id: 129,
            name: "Glucophage / Metformin 500mg",
            description: "First-line diabetes tablet.",
            image: "/img/diabetes1.jpg",
            rating: 5,
            reviews: 150,
            price: "Rs.30-40",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 130,
            name: "Diamicron MR 30/60mg (Gliclazide)",
            description: "Popular sulfonylurea for T2DM control.",
            image: "/img/diabetes2.jpg",
            rating: 4,
            reviews: 89,
            price: "Rs.400-440",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 131,
            name: "Tagipmet (Metformin + Sitagliptin)",
            description: "Effective combo (dual action).",
            image: "/img/diabetes3.jpg",
            rating: 5,
            reviews: 65,
            price: "Rs.712-760",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 132,
            name: "Daplyza Mxr (Dapagliflozin + Metformin)",
            description: "SGLT2 + Metformin combo.",
            image: "/img/diabetes4.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.308-483",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 133,
            name: "Erli 25mg (Empagliflozin)",
            description: "Good option for T2DM with cardio benefits.",
            image: "/img/diabetes5.jpg",
            rating: 4,
            reviews: 50,
            price: "Rs.647",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 134,
            name: "Diabetron CR 60mg",
            description: "Controlled-release oral antidiabetic.",
            image: "/img/diabetes6.jpg",
            rating: 4,
            reviews: 32,
            price: "Rs.671",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 135,
            name: "Trevia R2 (Vildagliptin + Metformin)",
            description: "DPP-4 inhibitor + Metformin combo.",
            image: "/img/diabetes7.jpg",
            rating: 4,
            reviews: 40,
            price: "Rs.732",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 136,
            name: "Jardy Met / Xenglu Met (Empagliflozin + Me...)",
            description: "Dual action, widespread use.",
            image: "/img/diabetes8.jpg",
            rating: 5,
            reviews: 78,
            price: "Rs.400-616",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 137,
            name: "Vildomet (Vildagliptin + Metformin)",
            description: "Popular dual therapy.",
            image: "/img/diabetes9.jpg",
            rating: 4,
            reviews: 55,
            price: "Rs.480",
            type: "Tablet",
            sickness: "Diabetes",
        },
        {
            id: 138,
            name: "Novonorm 1mg",
            description: "Stimulates insulin secretion.",
            image: "/img/diabetes10.jpg",
            rating: 4,
            reviews: 28,
            price: "Rs.1409",
            type: "Tablet",
            sickness: "Diabetes",
        },
        // Thyroid Medicines
        {
            id: 139,
            name: "Thyronorm 25 mcg (100’s)",
            description: "Standard levothyroxine sodium for hypothyroidism.",
            image: "/img/thyroid1.jpg",
            rating: 5,
            reviews: 120,
            price: "Rs.166-201",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 140,
            name: "Thyronorm 50 mcg (100’s)",
            description: "Effective thyroid hormone replacement therapy.",
            image: "/img/thyroid2.jpg",
            rating: 4,
            reviews: 95,
            price: "Rs.232",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 141,
            name: "Thyronorm 75 mcg (100’s)",
            description: "Daily thyroid maintenance dosage.",
            image: "/img/thyroid3.jpg",
            rating: 4,
            reviews: 88,
            price: "Rs.231-250",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 142,
            name: "Thyronorm 100 mcg (100’s)",
            description: "High strength levothyroxine.",
            image: "/img/thyroid4.jpg",
            rating: 5,
            reviews: 150,
            price: "Rs.252-332",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 143,
            name: "Thyronorm 125 mcg (100’s)",
            description: "Precise dosage for hormonal balance.",
            image: "/img/thyroid5.jpg",
            rating: 4,
            reviews: 62,
            price: "Rs.255-380",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 144,
            name: "Eltroxin 100 mcg (100’s)",
            description: "Treating underactive thyroid gland.",
            image: "/img/thyroid6.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.2500-4600",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 145,
            name: "Euthyrox 100 mcg (Imported, 50’s)",
            description: "Premium imported thyroid medication.",
            image: "/img/thyroid11.jpg",
            rating: 5,
            reviews: 30,
            price: "Rs.2200",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 146,
            name: "Euthyrox 50 mcg (Imported, 50’s)",
            description: "Imported lower dosage option.",
            image: "/img/thyroid8.jpg",
            rating: 5,
            reviews: 28,
            price: "Rs.2000",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 147,
            name: "BD Cytomel 25 mcg (100’s)",
            description: "T3 Liothyronine for specific conditions.",
            image: "/img/thyroid9.jpg",
            rating: 4,
            reviews: 15,
            price: "Rs.4800-5500",
            type: "Tablet",
            sickness: "Thyroid",
        },
        {
            id: 148,
            name: "MediTech Cytomel T3 25 mcg (100’s)",
            description: "Specialist T3 thyroid medication.",
            image: "/img/thyroid10.jpg",
            rating: 4,
            reviews: 12,
            price: "Rs.5500",
            type: "Tablet",
            sickness: "Thyroid",
        },

        // Malaria Medicines

        {
            id: 149,
            name: "Gen-M 80/480mg (Artemether + Lumefantrine)",
            description: "Standard first-line malaria treatment.",
            image: "/img/malaria1.jpg",
            rating: 5,
            reviews: 120,
            price: "Rs.580-650",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 150,
            name: "Artheget DS 40/240mg",
            description: "Artemether/Lumefantrine combo.",
            image: "/img/malaria2.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.409",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 151,
            name: "Artheget EZ 80/480mg",
            description: "More potent combo form.",
            image: "/img/malaria3.jpg",
            rating: 4,
            reviews: 28,
            price: "Rs.575",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 152,
            name: "A-Fantrine 20/120mg",
            description: "Artemether/Lumefantrine.",
            image: "/img/malaria4.jpg",
            rating: 4,
            reviews: 32,
            price: "Rs.272",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 153,
            name: "Arceva 80/480mg",
            description: "Strong combo antimalarial.",
            image: "/img/malaria5.jpg",
            rating: 4,
            reviews: 18,
            price: "Rs.620-630",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 154,
            name: "Arceva 40/240mg",
            description: "Standard strength combo.",
            image: "/img/malaria6.jpg",
            rating: 4,
            reviews: 15,
            price: "Rs.450-500",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 155,
            name: "Artem DS Plus 80/480mg",
            description: "Combo therapy for falciparum malaria.",
            image: "/img/malaria7.jpg",
            rating: 4,
            reviews: 12,
            price: "Rs.650",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 156,
            name: "Falume 20/120mg",
            description: "Budget combo option.",
            image: "/img/malaria8.jpg",
            rating: 4,
            reviews: 10,
            price: "Rs.150",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 157,
            name: "Malafantrine PF 40/240mg",
            description: "Generic combo therapy.",
            image: "/img/malaria9.jpg",
            rating: 4,
            reviews: 8,
            price: "Rs.264",
            type: "Tablet",
            sickness: "Malaria",
        },
        {
            id: 158,
            name: "Oxyclor 200mg (Hydroxychloroquine)",
            description: "Used in malaria prevention & mild treatment.",
            image: "/img/malaria10.jpg",
            rating: 4,
            reviews: 25,
            price: "Rs.479",
            type: "Tablet",
            sickness: "Malaria",
        },

        // Anxiety Medicines
        {
            id: 159,
            name: "Escitalopram (Cipralex)",
            description: "One of the most commonly used for anxiety & depression.",
            image: "/img/anxiety1.jpg",
            rating: 5,
            reviews: 210,
            price: "Rs.300-1270",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 160,
            name: "Citalopram (Lexapram)",
            description: "Effective and widely used for generalized anxiety.",
            image: "/img/anxiety2.jpg",
            rating: 5,
            reviews: 185,
            price: "Rs.332",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 161,
            name: "Sertraline (Zoloft)",
            description: "Common anxiety med internationally.",
            image: "/img/anxiety3.jpg",
            rating: 5,
            reviews: 95,
            price: "Rs.2600",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 162,
            name: "Paroxetine (Seroxat)",
            description: "Used for panic & anxiety disorders.",
            image: "/img/anxiety4.jpg",
            rating: 4,
            reviews: 120,
            price: "Rs.999",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 163,
            name: "Buspirone (Busron)",
            description: "Lower sedation & non-addictive option.",
            image: "/img/anxiety5.jpg",
            rating: 4,
            reviews: 65,
            price: "Rs.640",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 164,
            name: "Alprazolam (Zenith)",
            description: "Fast-acting anxiety relief.",
            image: "/img/anxiety6.jpg",
            rating: 4,
            reviews: 200,
            price: "Rs.300-529",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 165,
            name: "Xanax (Alprazolam)",
            description: "Quick relief for panic/acute anxiety.",
            image: "/img/anxiety7.jpg",
            rating: 5,
            reviews: 310,
            price: "Rs.4000-6000",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 166,
            name: "Bromazepam (Lexotanil)",
            description: "Used for anxiety & stress; milder than some benzos.",
            image: "/img/anxiety8.jpg",
            rating: 4,
            reviews: 150,
            price: "Rs.264-715",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 167,
            name: "Lorazepam (Tranquil 1mg)",
            description: "Very low cost; fast relief but habit-forming.",
            image: "/img/anxiety9.jpg",
            rating: 4,
            reviews: 80,
            price: "Rs.58-70",
            type: "Tablet",
            sickness: "Anxiety",
        },
        {
            id: 168,
            name: "Duloxetine",
            description: "Treats anxiety + chronic pain/depression.",
            image: "/img/anxiety10.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.360",
            type: "Tablet",
            sickness: "Anxiety",
        },

        // bacteria

        {
            id: 169,
            name: "Amoxil",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria1.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.215",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 170,
            name: "Augmentin",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria2.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.730",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 171,
            name: "Bactcid",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria3.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.380-420",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 172,
            name: "Uzaril",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria4.jpg",
            rating: 2,
            reviews: 45,
            price: "Rs.395-450",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 173,
            name: "Bacticzith",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria5.jpg",
            rating: 3,
            reviews: 45,
            price: "Rs.540-600",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 174,
            name: "Leflox",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria6.jpg",
            rating: 1,
            reviews: 45,
            price: "Rs.760",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 175,
            name: "Cephalexin",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria7.jpg",
            rating: 2,
            reviews: 45,
            price: "Rs.300-640",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 176,
            name: "Oxidil",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria8.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.495-1245",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 177,
            name: "Septran DS",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria9.jpg",
            rating: 3,
            reviews: 45,
            price: "Rs.495",
            type: "Tablet",
            sickness: "Bacteria",
        },
        {
            id: 178,
            name: "Fudic",
            description: "Treats bacteria + chronic pain/depression.",
            image: "/img/bacteria10.jpg",
            rating: 4,
            reviews: 45,
            price: "Rs.165-410",
            type: "Tablet",
            sickness: "Bacteria",
        },

        // Eye Infection


    ];

    // Extract unique diseases from the medicines list
    const existingDiseases = [...new Set(medicines.map((m) => m.sickness))];

    // Mock API: Add diseases that don't have medicines yet

    const additionalDiseases = [


        
        "Eye Infections",
        "Dental Care",
        "Piles",
        "Constipation",
        "Vitamins",
        "Flu"
    ];

    // Combine all diseases and sort them alphabetically
    const allDiseases = [...new Set([...existingDiseases, ...additionalDiseases])].sort();

    // Filter medicines based on search
    const filteredMedicines = medicines.filter((medicine) =>
        medicine.sickness.toLowerCase().includes(searchTerm.toLowerCase()) ||
        medicine.name.toLowerCase().includes(searchTerm.toLowerCase())
    );

    // Check if the search term matches a disease that has no medicines
    const matchedEmptyDisease = additionalDiseases.find(
        (disease) =>
            disease.toLowerCase().includes(searchTerm.toLowerCase()) &&
            !existingDiseases.includes(disease) &&
            searchTerm.length > 2
    );

    return (
        <div className="min-h-screen pt-32 pb-12 bg-gray-50">
            <div className="w-[90%] md:w-[80%] mx-auto">
                <div className="flex flex-col md:flex-row md:items-end justify-between mb-8 gap-4">
                    <div>
                        <p className="text-black text-2xl mt-1">
                            Browse our complete collection of medicines and supplements
                        </p>
                    </div>

                    <div className="flex gap-2 w-full md:w-auto">
                        <div className="relative flex-1 md:w-80">
                            <input
                                type="text"
                                placeholder="Search for disease (e.g., Sugar, Fever)..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="w-full mt-3 px-4 py-2 pl-10 bg-white border rounded-lg text-sm text-gray-600 focus:outline-none focus:ring-2 focus:ring-teal-500"
                            />
                            <svg
                                className="w-4 h-4 mt-2 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                            >
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                            </svg>
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                    {filteredMedicines.map((medicine) => (
                        <MedicineCard key={medicine.id} medicine={medicine} />
                    ))}
                </div>

                {filteredMedicines.length === 0 && (
                    <div className="col-span-full text-center py-12 text-gray-500">
                        {matchedEmptyDisease ? (
                            <div className="flex flex-col items-center">
                                <div className="w-16 h-16 bg-teal-50 rounded-full flex items-center justify-center mb-4 text-teal-500">
                                    <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                    </svg>
                                </div>
                                <h3 className="text-lg font-semibold text-gray-900">
                                    {matchedEmptyDisease} Category Available
                                </h3>
                                <p className="text-gray-500 max-w-sm mt-2">
                                    We have a category for {matchedEmptyDisease}, but no medicines are currently listed.
                                </p>
                            </div>
                        ) : (
                            <span>No medicines found for "{searchTerm}"</span>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}

const MedicineCard = ({ medicine }) => {
    return (
        <div className="bg-white rounded-xl shadow-sm hover:shadow-md transition overflow-hidden border flex flex-col h-full">
            <div className="relative h-40">
                <Image
                    src={medicine.image}
                    alt={medicine.name}
                    fill
                    className="object-cover"
                />
                <span className="absolute top-2 right-2 bg-white/90 backdrop-blur-sm px-2 py-0.5 rounded text-[10px] font-semibold text-gray-700">
                    {medicine.type}
                </span>
            </div>

            <div className="p-4 flex flex-col flex-1">
                <div className="flex justify-between items-start mb-1 gap-2">
                    <h3 className="text-sm font-bold text-gray-900 leading-tight">
                        {medicine.name}
                    </h3>
                    <span className="font-bold text-teal-600 text-sm whitespace-nowrap">
                        {medicine.price}
                    </span>
                </div>

                <p className="text-xs text-gray-500 mb-3 line-clamp-2">
                    {medicine.description}
                </p>

                <div className="mt-auto">
                    <div className="flex items-center mb-3">
                        <div className="flex text-yellow-400">
                            {[...Array(5)].map((_, i) => (
                                <svg
                                    key={i}
                                    className={`w-3 h-3 ${i < medicine.rating ? "fill-current" : "text-gray-200"
                                        }`}
                                    viewBox="0 0 20 20"
                                >
                                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                                </svg>
                            ))}
                        </div>
                        <span className="text-[10px] text-gray-400 ml-1">
                            ({medicine.reviews})
                        </span>
                    </div>

                    <button className="w-full border border-teal-100 bg-teal-50/50 text-teal-700 rounded-lg py-2 text-xs font-medium hover:bg-teal-100 transition-colors">
                        View Details
                    </button>
                </div>
            </div>
        </div>
    );
};


export default MedicinePage;
